In [2]:
import pandas as pd
data = {'Name':['Alice','Bob'],'Age':[25,30]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [5]:
import pandas as pd
lst = [['Alice',25],['Bob',30]]
df = pd.DataFrame(lst,columns=['Name','Age'])
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [7]:
import pandas as pd
lst = [['Alice',25],['Bob',30],['Anu',35],['Krishna',35],['Hena',46],['Parvathi',45]]
df = pd.DataFrame(lst,columns=['Name','Age'])
print(df)
df.head()

       Name  Age
0     Alice   25
1       Bob   30
2       Anu   35
3   Krishna   35
4      Hena   46
5  Parvathi   45

      Name  Age
0    Alice   25
1      Bob   30
2      Anu   35
3  Krishna   35
4     Hena   46

In [8]:
import pandas as pd
lst = [['Alice',25],['Bob',30]]
df = pd.DataFrame(lst,columns=['Name','Age'])
print(df)
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

    Name  Age
0  Alice   25
1    Bob   30

In [9]:
import pandas as pd
lst = [['Alice',25],['Bob',30],['Anu',35],['Krishna',35],['Hena',46],['Parvathi',45]]
df = pd.DataFrame(lst,columns=['Name','Age'])
print(df)
df.tail()

       Name  Age
0     Alice   25
1       Bob   30
2       Anu   35
3   Krishna   35
4      Hena   46
5  Parvathi   45

       Name  Age
1       Bob   30
2       Anu   35
3   Krishna   35
4      Hena   46
5  Parvathi   45

In [10]:
import pandas as pd
lst = [['Alice',25],['Bob',30],['Anu',35],['Krishna',35],['Hena',46],['Parvathi',45]]
df = pd.DataFrame(lst,columns=['Name','Age'])
print(df)
df.info()

       Name  Age
0     Alice   25
1       Bob   30
2       Anu   35
3   Krishna   35
4      Hena   46
5  Parvathi   45
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     6 non-null      int64
dtypes: int64(1), str(1)
memory usage: 228.0 bytes

In [11]:
import pandas as pd
lst = [['Alice',25],['Bob',30],['Anu',35],['Krishna',35],['Hena',46],['Parvathi',45]]
df = pd.DataFrame(lst,columns=['Name','Age'])
print(df)
df.describe()

       Name  Age
0     Alice   25
1       Bob   30
2       Anu   35
3   Krishna   35
4      Hena   46
5  Parvathi   45

             Age
count   6.000000
mean   36.000000
std     8.246211
min    25.000000
25%    31.250000
50%    35.000000
75%    42.500000
max    46.000000

In [12]:
import pandas as pd
lst = [['Alice',25],['Bob',30],['Anu',35],['Krishna',35],['Hena',46],['Parvathi',45]]
df = pd.DataFrame(lst,columns=['Name','Age'])
df['Name']

0       Alice
1         Bob
2         Anu
3     Krishna
4        Hena
5    Parvathi
Name: Name, dtype: str

In [14]:
import pandas as pd
lst = [['Alice',25],['Bob',30],['Anu',35],['Krishna',35],['Hena',46],['Parvathi',45]]
df = pd.DataFrame(lst,columns=['Name','Age'])
df[['Name','Age']]

       Name  Age
0     Alice   25
1       Bob   30
2       Anu   35
3   Krishna   35
4      Hena   46
5  Parvathi   45

In [15]:
import pandas as pd
lst = [['Alice',25],['Bob',30],['Anu',35],['Krishna',35],['Hena',46],['Parvathi',45]]
df = pd.DataFrame(lst,columns=['Name','Age'])
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [16]:
import pandas as pd
lst = [['Alice',25],['Bob',30],['Anu',35],['Krishna',35],['Hena',46],['Parvathi',45]]
df = pd.DataFrame(lst,columns=['Name','Age'])
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [19]:
import pandas as pd
lst = [['Jithu',18],['Alice',25],['Bob',30],['Anu',35],['Krishna',35],['Hena',46],['Parvathi',45]]
df = pd.DataFrame(lst,columns=['Name','Age'])
df[df['Age'] > 25]

       Name  Age
2       Bob   30
3       Anu   35
4   Krishna   35
5      Hena   46
6  Parvathi   45

In [24]:
import pandas as pd
lst = [['Jithu',18],['Alice',25],['Bob',30],['Anu',35],['Krishna',35],['Hena',46],['Parvathi',45]]
df = pd.DataFrame(lst,columns=['Name','Age'])
df['Gender']=['M','F','M','M','F','F','F']
df

       Name  Age Gender
0     Jithu   18      M
1     Alice   25      F
2       Bob   30      M
3       Anu   35      M
4   Krishna   35      F
5      Hena   46      F
6  Parvathi   45      F

In [26]:
import pandas as pd
lst = [['Jithu',18],['Alice',25],['Bob',30],['Anu',35],['Krishna',35],['Hena',46],['Parvathi',45]]
df = pd.DataFrame(lst,columns=['Name','Age'])
df['Gender']=['M','F','M','M','F','F','F']
df.drop('Age', axis=1, inplace=True)
df

       Name Gender
0     Jithu      M
1     Alice      F
2       Bob      M
3       Anu      M
4   Krishna      F
5      Hena      F
6  Parvathi      F

In [34]:
df.isnull()

    Name    Age  Gender
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False

In [30]:
df.dropna()

       Name  Age Gender
0     Jithu   18      M
1     Alice   25      F
2       Bob   30      M
3       Anu   35      M
4   Krishna   35      F
5      Hena   46      F
6  Parvathi   45      F

In [33]:
df.fillna(0)

       Name  Age Gender
0     Jithu   18      M
1     Alice   25      F
2       Bob   30      M
3       Anu   35      M
4   Krishna   35      F
5      Hena   46      F
6  Parvathi   45      F

In [35]:
df.groupby('Gender')['Age'].mean()

Gender
F    37.750000
M    27.666667
Name: Age, dtype: float64

In [37]:
import pandas as pd
df1=pd.DataFrame({'key':[1,2,3],'Name':['Alice','Bob','Jithu']})
df2=pd.DataFrame({'key':[1,2,3],'Age':[25,30,18]})
pd.merge(df1, df2, on='key')

   key   Name  Age
0    1  Alice   25
1    2    Bob   30
2    3  Jithu   18

In [44]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Anu'],'Age': [25, 30, 21]}
df = pd.DataFrame(data)
df.to_csv('data.csv', index=False)
df

    Name  Age
0  Alice   25
1    Bob   30
2    Anu   21

In [45]:
df.sort_values('Age')

    Name  Age
2    Anu   21
0  Alice   25
1    Bob   30

In [46]:
df.sort_values('Name')

    Name  Age
0  Alice   25
2    Anu   21
1    Bob   30

In [47]:
df['Age'].apply(lambda x: x + 1)

0    26
1    31
2    22
Name: Age, dtype: int64

In [48]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob', 'Anu']
Length: 3, dtype: str

In [49]:
import pandas as pd
data = {'Name': ['Alice', 'Anu', 'Anu'],'Age': [25, 30, 21]}
df = pd.DataFrame(data)
df.to_csv('data.csv', index=False)
df

    Name  Age
0  Alice   25
1    Anu   30
2    Anu   21

In [50]:
df['Name'].unique()

<StringArray>
['Alice', 'Anu']
Length: 2, dtype: str

In [51]:
df['Age'].value_counts()

Age
25    1
30    1
21    1
Name: count, dtype: int64

In [53]:
import pandas as pd
data = {'Name': ['Alice', 'Anu', 'Anu'],'Age': [21, 30, 21]}
df = pd.DataFrame(data)
df.to_csv('data.csv', index=False)
df

    Name  Age
0  Alice   21
1    Anu   30
2    Anu   21

In [54]:
df['Age'].value_counts()

Age
21    2
30    1
Name: count, dtype: int64